github.com:
    git_protocol: https
    users:
        JHill6253:
        john-morrigan:
    user: john-morrigan
github.gatech.edu:
    git_protocol: https
    users:
        jhill381:
    user: jhill381
